### ISSUE TITLE
We should be able to change the status_code on Resource

### ISSUE THREAD

**Issue by rfschubert** [MasoniteFramework/api#6]
By default, the status code is `200` if success, we should be able to force response other `HTTP codes` like `400, 403, 201` in a easy way.

maybe something like

```python 
return {...}, 403
```

**Comment by thetonus** [comment]
I think we need to keep this consistent with how we do it in the core repo. If you already have the `request: Request` class in the controller method, you can do `request.status(403)` anywhere in the controller. You can then return the `json` object or whatever you want.

**Comment by josephmancuso** [comment]
yeah this is actually solved. Before you could not even set the status code in the controller method in 2.1. A minor release fixed that. You can technically achieve this by extending the response class and adding (for shits and giggles) something like:

```python
# inside a service provider

def boot(response: Response, request: Request):
    self.request = request

    # extend is actually a really cool and rarely used method
    # on the response and request classes.
    response.extend('__irshift__', self._change_status_code)

def _change_status_code(self, status_code):
    self.request.status(status_code)
```

something like that? and then inside your controller method do something like:

```python
def show(self, response: Response):
    return response.json({'something': 'here'}) >>= 403
```

Bascially override a special method in order to add some syntax for changing status codes.

I actually have no idea if this works but thats an idea.

**Comment by rfschubert** [comment]
i'm trying to change the response code on version `0.0.3` without success yet.

this is my code right now

```python
    def delete(self, request: Request):
        __reason_id = request.param('id')

        __reason = self.model.where('id', __reason_id).first()

        if __reason:
            __reason.delete()
            return self.__response({
                "deleted": True
            })

        request.status(400)

        return self.__response_error('not_found', {
            "deleted": False,
            "error": self.model.ERRORS.DOCUMENT_NOT_EXISTS,
            "message": "Reason not exists"
        })
```

i tried those ways

`request.status(400)`
`self.request.status(400)`

both without success

**Comment by josephmancuso** [comment]
now fixed. This was actually an issue in core
